#This creates the name space in which all the resources bellow will be deployed
apiVersion: v1
kind: Namespace
metadata:
  name: carlos
---
apiVersion: v1
data:
  .dockerconfigjson: eyJhdXRocyI6eyJodHRwczovL2luZGV4LmRvY2tlci5pby92MS8iOnsidXNlcm5hbWUiOiJsaXphdHdpc3Rsb2NrIiwicGFzc3dvcmQiOiJQYSQkd29yZDEhIiwiZW1haWwiOiJsbGVjaHRtYW5AcGFsb2FsdG9uZXR3b3Jrcy5jb20iLCJhdXRoIjoiYkdsNllYUjNhWE4wYkc5amF6cFFZU1FrZDI5eVpERWgifX19
kind: Secret
metadata:
  name: runtime-sanity-secrets
  namespace: carlos
type: kubernetes.io/dockerconfigjson
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: carlos-centos
  namespace: carlos
  labels:
    app: carlos-centos
spec:
  replicas: 1
  selector:
    matchLabels:
      app: carlos-centos
  template:
    metadata:
      labels:
        app: carlos-centos
    spec:
      imagePullSecrets:
      - name: runtime-sanity-secrets
      nodeSelector:
        kubernetes.io/os: "linux"
      containers:
      - name: carlos-centos-eks-scale
        image: lizatwistlock/runtime_sanity:centos8-runtime-sanity
        command: [ "/bin/bash", "-c" ]
        args:
        - |
          while true; do
            ./run_all_runtime_containers.sh
            sleep 30
          done
        imagePullPolicy: Always
